### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by Christabelle143** [Christabelle143/react-group-project#25]
- Followed the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in order to copy the [[TEMPLATE] React Group Project](https://github.com/microverseinc/curriculum-react-redux/projects/1) board.
- Opened the GitHub project (Kanban board) in our team repo.
- Made sure that the card titles include: Setup, Fetch data, Lists render, Actions, Conditional components, Filters.
- Removed all cards with Team3 in the title.
- Ensured that Each of the team members assigned themselves to the cards from all categories 
- Ensured that all cards on our Kanban board had assignees.

Link to project: https://github.com/Christabelle143/react-group-project

This team consists of two members: @Ceemos96 and @Christabelle143.

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️ 
- Tasks distributed equally✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
